spring:
  cloud:
    dataflow:
      task:
        platform:
          local:
            accounts:
              default:
                docker-network: cinelog_default
                delete-container-on-exit: true
