/* ============================================================
   SEED #2 — MEDIA (100 reais: filmes + séries)
   Banco: MySQL 8+ (após migrations). Isto dispara os gatilhos
   de audit para "media" (ok, colunas permitem NULL nos metadados).
   ============================================================ */

START TRANSACTION;

INSERT INTO media (title, type, release_year, original_title, original_language, poster_url, backdrop_url, overview)
VALUES
  -- ===================== FILMES (≈60) =====================
  ('The Godfather', 'MOVIE', 1972, 'The Godfather', 'en', NULL, NULL, NULL),
  ('The Godfather Part II', 'MOVIE', 1974, 'The Godfather Part II', 'en', NULL, NULL, NULL),
  ('The Dark Knight', 'MOVIE', 2008, 'The Dark Knight', 'en', NULL, NULL, NULL),
  ('Pulp Fiction', 'MOVIE', 1994, 'Pulp Fiction', 'en', NULL, NULL, NULL),
  ('Schindler''s List', 'MOVIE', 1993, 'Schindler''s List', 'en', NULL, NULL, NULL),
  ('The Lord of the Rings: The Fellowship of the Ring', 'MOVIE', 2001, 'The Lord of the Rings: The Fellowship of the Ring', 'en', NULL, NULL, NULL),
  ('The Lord of the Rings: The Return of the King', 'MOVIE', 2003, 'The Lord of the Rings: The Return of the King', 'en', NULL, NULL, NULL),
  ('Inception', 'MOVIE', 2010, 'Inception', 'en', NULL, NULL, NULL),
  ('Fight Club', 'MOVIE', 1999, 'Fight Club', 'en', NULL, NULL, NULL),
  ('Forrest Gump', 'MOVIE', 1994, 'Forrest Gump', 'en', NULL, NULL, NULL),
  ('The Matrix', 'MOVIE', 1999, 'The Matrix', 'en', NULL, NULL, NULL),
  ('Goodfellas', 'MOVIE', 1990, 'Goodfellas', 'en', NULL, NULL, NULL),
  ('Se7en', 'MOVIE', 1995, 'Se7en', 'en', NULL, NULL, NULL),
  ('The Silence of the Lambs', 'MOVIE', 1991, 'The Silence of the Lambs', 'en', NULL, NULL, NULL),
  ('Interstellar', 'MOVIE', 2014, 'Interstellar', 'en', NULL, NULL, NULL),
  ('Parasite', 'MOVIE', 2019, '기생충', 'ko', NULL, NULL, NULL),
  ('Spirited Away', 'MOVIE', 2001, '千と千尋の神隠し', 'ja', NULL, NULL, NULL),
  ('City of God', 'MOVIE', 2002, 'Cidade de Deus', 'pt', NULL, NULL, NULL),
  ('The Pianist', 'MOVIE', 2002, 'The Pianist', 'en', NULL, NULL, NULL),
  ('Gladiator', 'MOVIE', 2000, 'Gladiator', 'en', NULL, NULL, NULL),
  ('Saving Private Ryan', 'MOVIE', 1998, 'Saving Private Ryan', 'en', NULL, NULL, NULL),
  ('Whiplash', 'MOVIE', 2014, 'Whiplash', 'en', NULL, NULL, NULL),
  ('The Green Mile', 'MOVIE', 1999, 'The Green Mile', 'en', NULL, NULL, NULL),
  ('The Usual Suspects', 'MOVIE', 1995, 'The Usual Suspects', 'en', NULL, NULL, NULL),
  ('Léon: The Professional', 'MOVIE', 1994, 'Léon', 'fr', NULL, NULL, NULL),
  ('Life Is Beautiful', 'MOVIE', 1997, 'La vita è bella', 'it', NULL, NULL, NULL),
  ('The Intouchables', 'MOVIE', 2011, 'Intouchables', 'fr', NULL, NULL, NULL),
  ('The Prestige', 'MOVIE', 2006, 'The Prestige', 'en', NULL, NULL, NULL),
  ('The Departed', 'MOVIE', 2006, 'The Departed', 'en', NULL, NULL, NULL),
  ('The Lion King', 'MOVIE', 1994, 'The Lion King', 'en', NULL, NULL, NULL),
  ('Back to the Future', 'MOVIE', 1985, 'Back to the Future', 'en', NULL, NULL, NULL),
  ('Terminator 2: Judgment Day', 'MOVIE', 1991, 'Terminator 2: Judgment Day', 'en', NULL, NULL, NULL),
  ('Alien', 'MOVIE', 1979, 'Alien', 'en', NULL, NULL, NULL),
  ('Aliens', 'MOVIE', 1986, 'Aliens', 'en', NULL, NULL, NULL),
  ('Apocalypse Now', 'MOVIE', 1979, 'Apocalypse Now', 'en', NULL, NULL, NULL),
  ('American Beauty', 'MOVIE', 1999, 'American Beauty', 'en', NULL, NULL, NULL),
  ('Oldboy', 'MOVIE', 2003, '올드보이', 'ko', NULL, NULL, NULL),
  ('The Shining', 'MOVIE', 1980, 'The Shining', 'en', NULL, NULL, NULL),
  ('Amélie', 'MOVIE', 2001, 'Le fabuleux destin d''Amélie Poulain', 'fr', NULL, NULL, NULL),
  ('Toy Story', 'MOVIE', 1995, 'Toy Story', 'en', NULL, NULL, NULL),
  ('Toy Story 3', 'MOVIE', 2010, 'Toy Story 3', 'en', NULL, NULL, NULL),
  ('Coco', 'MOVIE', 2017, 'Coco', 'en', NULL, NULL, NULL),
  ('Pan''s Labyrinth', 'MOVIE', 2006, 'El laberinto del fauno', 'es', NULL, NULL, NULL),
  ('The Lives of Others', 'MOVIE', 2006, 'Das Leben der Anderen', 'de', NULL, NULL, NULL),
  ('Amadeus', 'MOVIE', 1984, 'Amadeus', 'en', NULL, NULL, NULL),
  ('Braveheart', 'MOVIE', 1995, 'Braveheart', 'en', NULL, NULL, NULL),
  ('Das Boot', 'MOVIE', 1981, 'Das Boot', 'de', NULL, NULL, NULL),
  ('The Great Dictator', 'MOVIE', 1940, 'The Great Dictator', 'en', NULL, NULL, NULL),
  ('12 Angry Men', 'MOVIE', 1957, '12 Angry Men', 'en', NULL, NULL, NULL),
  ('Good Will Hunting', 'MOVIE', 1997, 'Good Will Hunting', 'en', NULL, NULL, NULL),
  ('Heat', 'MOVIE', 1995, 'Heat', 'en', NULL, NULL, NULL),
  ('There Will Be Blood', 'MOVIE', 2007, 'There Will Be Blood', 'en', NULL, NULL, NULL),
  ('No Country for Old Men', 'MOVIE', 2007, 'No Country for Old Men', 'en', NULL, NULL, NULL),
  ('The Social Network', 'MOVIE', 2010, 'The Social Network', 'en', NULL, NULL, NULL),
  ('Mad Max: Fury Road', 'MOVIE', 2015, 'Mad Max: Fury Road', 'en', NULL, NULL, NULL),
  ('Joker', 'MOVIE', 2019, 'Joker', 'en', NULL, NULL, NULL),
  ('Avengers: Endgame', 'MOVIE', 2019, 'Avengers: Endgame', 'en', NULL, NULL, NULL),
  ('Dune', 'MOVIE', 2021, 'Dune', 'en', NULL, NULL, NULL),
  ('Dune: Part Two', 'MOVIE', 2024, 'Dune: Part Two', 'en', NULL, NULL, NULL),
  ('Oppenheimer', 'MOVIE', 2023, 'Oppenheimer', 'en', NULL, NULL, NULL),
  ('Barbie', 'MOVIE', 2023, 'Barbie', 'en', NULL, NULL, NULL),
  ('La La Land', 'MOVIE', 2016, 'La La Land', 'en', NULL, NULL, NULL),
  ('The Grand Budapest Hotel', 'MOVIE', 2014, 'The Grand Budapest Hotel', 'en', NULL, NULL, NULL),
  ('Her', 'MOVIE', 2013, 'Her', 'en', NULL, NULL, NULL),
  ('Blade Runner 2049', 'MOVIE', 2017, 'Blade Runner 2049', 'en', NULL, NULL, NULL),
  ('Drive', 'MOVIE', 2011, 'Drive', 'en', NULL, NULL, NULL),
  ('The Hunt', 'MOVIE', 2012, 'Jagten', 'da', NULL, NULL, NULL),
  ('Incendies', 'MOVIE', 2010, 'Incendies', 'fr', NULL, NULL, NULL),
  ('The Handmaiden', 'MOVIE', 2016, '아가씨', 'ko', NULL, NULL, NULL),
  ('Your Name', 'MOVIE', 2016, '君の名は。', 'ja', NULL, NULL, NULL),
  ('RRR', 'MOVIE', 2022, 'రౌద్రం రణం రుధిరం', 'te', NULL, NULL, NULL),
  ('Crouching Tiger, Hidden Dragon', 'MOVIE', 2000, '臥虎藏龍', 'zh', NULL, NULL, NULL),
  ('The Truman Show', 'MOVIE', 1998, 'The Truman Show', 'en', NULL, NULL, NULL),
  ('The Big Lebowski', 'MOVIE', 1998, 'The Big Lebowski', 'en', NULL, NULL, NULL),
  ('The Incredibles', 'MOVIE', 2004, 'The Incredibles', 'en', NULL, NULL, NULL),
  ('WALL·E', 'MOVIE', 2008, 'WALL·E', 'en', NULL, NULL, NULL),
  ('Up', 'MOVIE', 2009, 'Up', 'en', NULL, NULL, NULL),
  ('The Dark Knight Rises', 'MOVIE', 2012, 'The Dark Knight Rises', 'en', NULL, NULL, NULL),
  ('Guardians of the Galaxy', 'MOVIE', 2014, 'Guardians of the Galaxy', 'en', NULL, NULL, NULL),
  ('Spider-Man: Into the Spider-Verse', 'MOVIE', 2018, 'Spider-Man: Into the Spider-Verse', 'en', NULL, NULL, NULL),
  ('Spider-Man: Across the Spider-Verse', 'MOVIE', 2023, 'Spider-Man: Across the Spider-Verse', 'en', NULL, NULL, NULL),
  ('The Batman', 'MOVIE', 2022, 'The Batman', 'en', NULL, NULL, NULL),

  -- ===================== SÉRIES (≈40) =====================
  ('Breaking Bad', 'SERIES', 2008, 'Breaking Bad', 'en', NULL, NULL, NULL),
  ('Game of Thrones', 'SERIES', 2011, 'Game of Thrones', 'en', NULL, NULL, NULL),
  ('The Sopranos', 'SERIES', 1999, 'The Sopranos', 'en', NULL, NULL, NULL),
  ('The Wire', 'SERIES', 2002, 'The Wire', 'en', NULL, NULL, NULL),
  ('Friends', 'SERIES', 1994, 'Friends', 'en', NULL, NULL, NULL),
  ('The Office (US)', 'SERIES', 2005, 'The Office', 'en', NULL, NULL, NULL),
  ('The Office (UK)', 'SERIES', 2001, 'The Office', 'en', NULL, NULL, NULL),
  ('Stranger Things', 'SERIES', 2016, 'Stranger Things', 'en', NULL, NULL, NULL),
  ('The Crown', 'SERIES', 2016, 'The Crown', 'en', NULL, NULL, NULL),
  ('The Mandalorian', 'SERIES', 2019, 'The Mandalorian', 'en', NULL, NULL, NULL),
  ('The Last of Us', 'SERIES', 2023, 'The Last of Us', 'en', NULL, NULL, NULL),
  ('House of the Dragon', 'SERIES', 2022, 'House of the Dragon', 'en', NULL, NULL, NULL),
  ('Chernobyl', 'SERIES', 2019, 'Chernobyl', 'en', NULL, NULL, NULL),
  ('Band of Brothers', 'SERIES', 2001, 'Band of Brothers', 'en', NULL, NULL, NULL),
  ('True Detective', 'SERIES', 2014, 'True Detective', 'en', NULL, NULL, NULL),
  ('Fargo', 'SERIES', 2014, 'Fargo', 'en', NULL, NULL, NULL),
  ('Dark', 'SERIES', 2017, 'Dark', 'de', NULL, NULL, NULL),
  ('Narcos', 'SERIES', 2015, 'Narcos', 'es', NULL, NULL, NULL),
  ('Narcos: Mexico', 'SERIES', 2018, 'Narcos: Mexico', 'es', NULL, NULL, NULL),
  ('Black Mirror', 'SERIES', 2011, 'Black Mirror', 'en', NULL, NULL, NULL),
  ('Westworld', 'SERIES', 2016, 'Westworld', 'en', NULL, NULL, NULL),
  ('Succession', 'SERIES', 2018, 'Succession', 'en', NULL, NULL, NULL),
  ('Better Call Saul', 'SERIES', 2015, 'Better Call Saul', 'en', NULL, NULL, NULL),
  ('Mr. Robot', 'SERIES', 2015, 'Mr. Robot', 'en', NULL, NULL, NULL),
  ('The Boys', 'SERIES', 2019, 'The Boys', 'en', NULL, NULL, NULL),
  ('The Bear', 'SERIES', 2022, 'The Bear', 'en', NULL, NULL, NULL),
  ('Severance', 'SERIES', 2022, 'Severance', 'en', NULL, NULL, NULL),
  ('The Queen''s Gambit', 'SERIES', 2020, 'The Queen''s Gambit', 'en', NULL, NULL, NULL),
  ('The Witcher', 'SERIES', 2019, 'The Witcher', 'en', NULL, NULL, NULL),
  ('Vikings', 'SERIES', 2013, 'Vikings', 'en', NULL, NULL, NULL),
  ('The Handmaid''s Tale', 'SERIES', 2017, 'The Handmaid''s Tale', 'en', NULL, NULL, NULL),
  ('Money Heist (La Casa de Papel)', 'SERIES', 2017, 'La casa de papel', 'es', NULL, NULL, NULL),
  ('Attack on Titan', 'SERIES', 2013, '進撃の巨人', 'ja', NULL, NULL, NULL),
  ('Death Note', 'SERIES', 2006, 'DEATH NOTE', 'ja', NULL, NULL, NULL),
  ('Fullmetal Alchemist: Brotherhood', 'SERIES', 2009, '鋼の錬金術師 FULLMETAL ALCHEMIST', 'ja', NULL, NULL, NULL),
  ('One Piece', 'SERIES', 1999, 'ONE PIECE', 'ja', NULL, NULL, NULL),
  ('Avatar: The Last Airbender', 'SERIES', 2005, 'Avatar: The Last Airbender', 'en', NULL, NULL, NULL),
  ('Cowboy Bebop', 'SERIES', 1998, 'カウボーイビバップ', 'ja', NULL, NULL, NULL),
  ('Sherlock', 'SERIES', 2010, 'Sherlock', 'en', NULL, NULL, NULL),
  ('Peaky Blinders', 'SERIES', 2013, 'Peaky Blinders', 'en', NULL, NULL, NULL);

COMMIT;

-- conferência rápida
SELECT 'media_total' AS what, COUNT(*) AS total FROM media
UNION ALL SELECT 'movies', COUNT(*) FROM media WHERE type='MOVIE'
UNION ALL SELECT 'series', COUNT(*) FROM media WHERE type='SERIES'
ORDER BY what;
